<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="PaddleOcrNet" />
    <PackageReference Include="PaddleOcrNet.Gpu" />
    <PackageReference Include="PDFtoImage" />
    <PackageReference Include="PdfPig" />
    <PackageReference Include="PDFsharp" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" />
    <PackageReference Include="SQLitePCLRaw.core" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" />
    <PackageReference Include="SQLitePCLRaw.provider.e_sqlite3" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

</Project>
